title: 陆国松的编程笔记
email: luguosong8@163.com
#description: >- # this means to ignore newlines until "baseurl:"
#  编程学习笔记
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown

#排除一些文件和文件夹
exclude:
  - .idea/
  - .git/

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "许可证："

#回到顶部
back_to_top: true
back_to_top_text: 回到顶部⬆

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "在Github中编辑此页面."
gh_edit_repository: "https://github.com/guosonglu/code-notes" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# 这个使用的是小号，大号可能有安全隐患
gitment_owner: luguosong
gitment_repo: luguosong.github.io
gitment_oauth:
  client_id: 0d8aaec11145d797cdfa
  client_secret: 43cec67aeda473d51e3975f5f9ea4b2d60fb1cb3

color_scheme: dark
plugins:
  - jekyll-feed
  - jekyll-seo-tag


collections:
  java:
    output: true
  environment:
    output: true
  other:
    output: true

just_the_docs:
  collections:
    java:
      name: Java
    environment:
      name: 工具和环境
    other:
      name: 其它

aux_links:
  "code-notes on GitHub":
    - "//github.com/guosonglu/code-notes"

aux_links_new_tab: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # 将页面拆分为可单独搜索的部分
  # Supports 1 - 6, default: 2
  heading_level: 2
  # 每个搜索结果的最大预览量
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
